#!/usr/bin/env node
// scripts/generate-data.js
// Reads data.local.json and regenerates src/data.js.
// Use this when only local content changed (images, descriptions)
// and you don't need to pull from Notion.

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dir, '..')
const LOCAL_PATH = join(ROOT, 'src', 'data.local.json')
const OUT_PATH = join(ROOT, 'src', 'data.js')

function buildDataJs(items) {
  const lines = [
    '// Auto-generated by scripts/generate-data.js — do not edit manually',
    `// Last generated: ${new Date().toISOString()}`,
    'export const items = ([',
  ]

  for (let i = 0; i < items.length; i++) {
    const item = items[i]
    const comma = i < items.length - 1 ? ',' : ''
    lines.push('  {')
    for (const [key, val] of Object.entries(item)) {
      lines.push(`    ${key}: ${JSON.stringify(val)},`)
    }
    lines.push(`  }${comma}`)
  }

  lines.push(']).reverse()', '')
  return lines.join('\n')
}

function main() {
  const local = JSON.parse(readFileSync(LOCAL_PATH, 'utf8'))
  const items = Object.values(local)
    .map(item => ({
      id:           item.id,
      title:        item.title        ?? '',
      artist:       item.artist       ?? null,
      collective:   item.collective   ?? null,
      type:         item.type         ?? '',
      medium:       item.medium       ?? '',
      year:         item.year         ?? '',
      idea:         item.idea         ?? '',
      description:  item.description  ?? '',
      notes:        item.notes        ?? '',
      color:        item.color        ?? '#C8D5C0',
      image:        item.image        ?? null,
      imageOptions: item.imageOptions ?? [],
      sources:      item.sources      ?? [],
    }))
    .sort((a, b) => a.id - b.id)

  writeFileSync(OUT_PATH, buildDataJs(items))
  console.log(`✅  src/data.js generated from ${items.length} items in data.local.json`)
}

main()
