#!/usr/bin/env node
// scripts/sync-notion.js
// Fetches astroart database from Notion and merges with local overrides → src/data.js
// Run manually: NOTION_TOKEN=... NOTION_DB_ID=... node scripts/sync-notion.js

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dir, '..')

const TOKEN = process.env.NOTION_TOKEN?.trim()

function cleanDbId(raw) {
  if (!raw) return ''
  const match = raw.match(/([a-f0-9]{8}-?[a-f0-9]{4}-?[a-f0-9]{4}-?[a-f0-9]{4}-?[a-f0-9]{12}|[a-f0-9]{32})/i)
  return match ? match[1].replace(/-/g, '') : raw.trim()
}

const DB_ID = cleanDbId(process.env.NOTION_DB_ID)

if (!TOKEN || !DB_ID) {
  console.error('❌  Missing NOTION_TOKEN or NOTION_DB_ID environment variables')
  process.exit(1)
}

console.log(`🔑  DB_ID resolved to: ${DB_ID}`)

const HEADERS = {
  Authorization: `Bearer ${TOKEN}`,
  'Notion-Version': '2022-06-28',
  'Content-Type': 'application/json',
}

// ── Notion helpers ────────────────────────────────────────────────────────────

async function queryDatabase() {
  const results = []
  let cursor = undefined

  while (true) {
    const body = { page_size: 100, sorts: [{ property: '#', direction: 'ascending' }] }
    if (cursor) body.start_cursor = cursor

    const res = await fetch(`https://api.notion.com/v1/databases/${DB_ID}/query`, {
      method: 'POST',
      headers: HEADERS,
      body: JSON.stringify(body),
    })

    if (!res.ok) {
      const err = await res.text()
      throw new Error(`Notion API error ${res.status}: ${err}`)
    }

    const data = await res.json()
    results.push(...data.results)
    if (!data.has_more) break
    cursor = data.next_cursor
  }

  return results
}

function getText(prop) {
  if (!prop) return ''
  switch (prop.type) {
    case 'title':     return prop.title.map(t => t.plain_text).join('').trim()
    case 'rich_text': return prop.rich_text.map(t => t.plain_text).join('').trim()
    case 'number':    return prop.number != null ? String(prop.number) : ''
    case 'url':       return prop.url || ''
    case 'select':    return prop.select?.name || ''
    default:          return ''
  }
}

// "Lucien Rudaux, Sur les autres Mondes"  →  { artist, title }
function parseName(raw) {
  const i = raw.indexOf(',')
  if (i === -1) return { artist: null, title: raw.trim() }
  return { artist: raw.slice(0, i).trim(), title: raw.slice(i + 1).trim() }
}

// "Oil on canvas / Photography"  →  { type, medium }
function parseTypeMedium(raw) {
  const i = raw.indexOf('/')
  if (i === -1) return { type: raw.trim(), medium: '' }
  return { type: raw.slice(0, i).trim(), medium: raw.slice(i + 1).trim() }
}

// Split multi-URL source field (newline or space separated)
function parseSources(raw) {
  return raw.split(/\n+/).map(s => s.trim()).filter(s => s.startsWith('http'))
}

// ── Page body (notes) ─────────────────────────────────────────────────────────

async function fetchPageNotes(pageId) {
  const res = await fetch(`https://api.notion.com/v1/blocks/${pageId}/children?page_size=100`, {
    headers: HEADERS,
  })
  if (!res.ok) return ''
  const data = await res.json()
  return blocksToText(data.results)
}

function blockText(block) {
  const rt = block[block.type]?.rich_text
  return rt ? rt.map(t => t.plain_text).join('') : ''
}

function blocksToText(blocks) {
  return blocks
    .map(block => {
      switch (block.type) {
        case 'paragraph':          return blockText(block)
        case 'heading_1':          return `# ${blockText(block)}`
        case 'heading_2':          return `## ${blockText(block)}`
        case 'heading_3':          return `### ${blockText(block)}`
        case 'bulleted_list_item': return `• ${blockText(block)}`
        case 'numbered_list_item': return `${blockText(block)}`
        case 'quote':              return `"${blockText(block)}"`
        case 'divider':            return '---'
        default:                   return ''
      }
    })
    .filter(Boolean)
    .join('\n')
    .trim()
}

// ── Local overrides ───────────────────────────────────────────────────────────

function readLocal() {
  const path = join(ROOT, 'src/data.local.json')
  if (!existsSync(path)) return {}
  return JSON.parse(readFileSync(path, 'utf8'))
}

// ── Generate data.js ──────────────────────────────────────────────────────────

function buildDataJs(items) {
  const serialized = JSON.stringify(items, null, 2)
    .replace(/"([^"]+)":/g, '$1:')         // unquote keys
    .replace(/"/g, "'")                    // double → single quotes
    .replace(/'(https?:[^']+)'/g, "'$1'") // keep URLs as-is

  return [
    '// Auto-generated by scripts/sync-notion.js — do not edit manually',
    `// Last synced: ${new Date().toISOString()}`,
    `export const items = (${serialized}).reverse()`,
    '',
  ].join('\n')
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('📡  Fetching Notion database...')
  const pages = await queryDatabase()
  console.log(`    Found ${pages.length} pages`)

  const local = readLocal()

  console.log('📝  Fetching page notes...')
  const items = (await Promise.all(
    pages.map(async page => {
      const p = page.properties

      const idRaw = getText(p['#'])
      const id = idRaw ? parseInt(idRaw, 10) : null
      if (!id) return null

      const over = local[String(id)] || {}

      const name = getText(p['Name']) || ''
      const { artist: notionArtist, title: notionTitle } = parseName(name)
      const { type: notionType, medium: notionMedium } = parseTypeMedium(getText(p['Type / Medium']))

      // Fetch page body (notes written in Notion page content)
      const notes = await fetchPageNotes(page.id)

      // Local overrides win for all text fields (until Notion has Russian content)
      const title      = over.title      ?? notionTitle
      const artist     = over.artist     ?? notionArtist
      const collective = over.collective ?? null
      const type       = over.type       ?? notionType
      const medium     = over.medium     ?? notionMedium
      const year       = over.year       ?? getText(p['Year (approx.)'])
      const idea       = over.idea       ?? getText(p['Idea or Message'])
      const description= over.description ?? ''
      const sources    = parseSources(getText(p['Source']))

      return {
        id,
        title,
        artist,
        collective,
        type,
        medium,
        year,
        idea,
        description,
        notes,
        color:        over.color        ?? '#C8D5C0',
        image:        over.image        ?? null,
        imageOptions: over.imageOptions ?? [],
        sources,
      }
    })
  ))
    .filter(Boolean)
    .sort((a, b) => a.id - b.id)

  const outPath = join(ROOT, 'src/data.js')
  const before = existsSync(outPath) ? readFileSync(outPath, 'utf8') : ''
  const after = buildDataJs(items)

  if (before === after) {
    console.log('✅  No changes — data.js is already up to date')
    return
  }

  writeFileSync(outPath, after)
  console.log(`✅  data.js updated with ${items.length} items`)

  // Print summary of what changed
  console.log('\n📋  Items synced:')
  items.forEach(item => console.log(`    ${String(item.id).padStart(2, '0')}  ${item.artist ? item.artist + ' — ' : ''}${item.title}`))
}

main().catch(err => {
  console.error('❌ ', err.message)
  process.exit(1)
})
