export const items = [
  {
    id: 1,
    image: null,
    color: '#C8D5C0',
    artist: 'Chesley Bonestell',
    collective: null,
    type: 'Illustration',
    medium: 'Oil on board',
    title: 'Saturn as Seen from Titan',
    description: `A dramatic rendering of Saturn rising above the frozen methane plains of Titan, its rings tilted at a sharp angle against a star-filled sky. Bonestell's meticulous attention to planetary geometry made this one of the most reproduced astronomical artworks of the twentieth century.`,
    idea: 'The sublime scale of the solar system made tangible through the familiar horizon line',
    year: '1944',
  },
  {
    id: 2,
    image: null,
    color: '#1A1A2E',
    artist: 'Lucien Rudaux',
    collective: null,
    type: 'Painting',
    medium: 'Oil on canvas',
    title: 'Sur les autres Mondes',
    description: `Rudaux painted Mars not as a place of fantasy but as a geologist might imagine it — a cold, windswept desert lit by a pale sun. His surfaces predate the space age by decades yet align remarkably with later photographic evidence.`,
    idea: 'Scientific imagination as a form of prospective documentary',
    year: '1937',
  },
  {
    id: 3,
    image: null,
    color: '#2C1810',
    artist: 'Paul Calle',
    collective: null,
    type: 'Drawing',
    medium: 'Pencil on paper',
    title: 'Astronaut Suit Studies',
    description: `Commissioned by NASA to document the preparation for the Apollo 11 mission, Calle's pencil studies capture the physicality of suiting up — the layered materials, the constrained movement, the intimate ritual of preparing a human body to leave the atmosphere.`,
    idea: 'The body as a site of technological transformation',
    year: '1969',
  },
  {
    id: 4,
    image: null,
    color: '#0D1B2A',
    artist: 'Robert McCall',
    collective: null,
    type: 'Mural',
    medium: 'Acrylic on canvas',
    title: 'The Space Mural — A Cosmic View',
    description: `Spanning over fifteen meters in the National Air and Space Museum, McCall's mural compresses cosmic history into a single visual field. The sun blazes at centre, flanked by the arc of planetary formation and the distant smear of galaxies.`,
    idea: 'Public art as a vehicle for collective cosmological wonder',
    year: '1976',
  },
  {
    id: 5,
    image: null,
    color: '#3D2645',
    artist: 'Aleksei Leonov',
    collective: null,
    type: 'Painting',
    medium: 'Tempera',
    title: 'Over the Black Sea',
    description: `The first human to walk in space, Leonov also painted obsessively throughout his career, producing hundreds of works depicting orbital views, spacecraft, and the psychological experience of weightlessness. This painting shows the curvature of Earth seen from orbit, with the Black Sea rendered in deep cobalt.`,
    idea: 'First-hand witness as artistic authority',
    year: '1973',
  },
  {
    id: 6,
    image: null,
    color: '#1B3A2D',
    artist: 'Alan Bean',
    collective: null,
    type: 'Painting',
    medium: 'Acrylic on canvas with lunar dust',
    title: 'Approaching Surveyor',
    description: `Apollo 12 astronaut Alan Bean mixed actual lunar dust into his paint to physically bind his artworks to the Moon. His scenes are vibrant and expressionist — a deliberate departure from photo-realism, insisting on the emotional rather than the documentary register.`,
    idea: 'Material authenticity as a bridge between experience and representation',
    year: '1983',
  },
  {
    id: 7,
    image: null,
    color: '#2A2A1A',
    artist: 'Katsushika Hokusai',
    collective: null,
    type: 'Woodblock Print',
    medium: 'Ink and colour on paper',
    title: 'Comet over Edo',
    description: `Part of a lesser-known series depicting celestial phenomena, this print shows a comet arcing over rooftops while figures below pause in quiet observation. The comet's tail is rendered with the same fluid lines Hokusai used for ocean waves.`,
    idea: 'The sky as continuous with the earth — celestial events as communal experience',
    year: 'c.1835',
  },
  {
    id: 8,
    image: null,
    color: '#1C2B3A',
    artist: 'NASA / ESA',
    collective: 'Hubble Heritage Team',
    type: 'Photograph',
    medium: 'Digital composite, false colour',
    title: 'Pillars of Creation',
    description: `The original 1995 image and its 2014 remake — dense columns of hydrogen gas and dust in the Eagle Nebula, some stretching four light-years in length. The colour mapping translates wavelengths invisible to the human eye into a palette that has become iconographic.`,
    idea: `Scientific imaging as aesthetic choice: how instrumentation shapes perception`,
    year: '1995 / 2014',
  },
  {
    id: 9,
    image: null,
    color: '#3A1C1C',
    artist: 'Etienne Trouvelot',
    collective: null,
    type: 'Pastel Drawing',
    medium: 'Pastel on paper',
    title: 'Total Eclipse of the Sun',
    description: `Before astrophotography matured, Trouvelot produced some of the most detailed astronomical illustrations ever made, working directly from telescope observations. His 1882 solar eclipse study captures the corona's filamentary structure with uncanny accuracy.`,
    idea: 'The hand as a precision instrument; drawing as seeing',
    year: '1882',
  },
  {
    id: 10,
    image: null,
    color: '#0A0A14',
    artist: 'Michael Benson',
    collective: null,
    type: 'Photography',
    medium: 'Digital print from spacecraft data',
    title: 'Planetfall',
    description: `Assembled from raw data transmitted by planetary probes — Voyager, Cassini, Mars Reconnaissance Orbiter — Benson processes images that no human eye has directly seen. His prints are vast, sometimes several metres wide, and strip away the scientific annotation to leave pure visual encounter.`,
    idea: 'Remote sensing as a form of landscape photography',
    year: '2002–ongoing',
  },
]
